// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config';
import * as dotenv from 'dotenv';

// Явно завантажуємо змінні з .env файлу
dotenv.config();

export default defineConfig({
  datasource: {
    // Тепер process.env.DATABASE_URL точно буде заповненим
    url: process.env.DATABASE_URL,
  },
});
